name: py37
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.0
  - ipython
  # - tqdm
  - matplotlib
  # - pylint
  # - conda-forge::jupyterlab
  # - conda-forge::h5py=3.1.0
  # - conda-forge::loguru=0.5.3
  # - conda-forge::scipy
  # - conda-forge::numba
  # - conda-forge::ipdb
  # - conda-forge::albumentations=0.5.1
  - pip
  - pip:
    - -r requirements.txt